Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopping.Filters;
using WebShopping.Models;
using WebShopping.Repos.Implementation;
using WebShopping.Repos.Interface;

namespace WebShopping.Controllers
{
    [AuthorizeXS]
    [BossOnly]
    public class AdminController : BaseController
    {
        private readonly IAdminRepo _adminRepo;
        public AdminController(IAdminRepo adminRepo)
        {
            _adminRepo = adminRepo;
        }

        public ActionResult Index()
        {
            return View(_adminRepo.GetAll());
        }

        [HttpGet]
        [Route("Add")]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Admin admin)
        {
            admin.IsBoss = false;
            admin.Password = SimpleEncryptor.Encrypt("13589100sS");
            ModelState["Password"].Errors.Clear();
            if (ModelState.IsValid)
            {
                if (_adminRepo.Add(admin) == HttpStatusCode.OK)
                {
                    TempData["Added"] = $"{Resources.Resources.AdminInsert}";
                }
                else
                {
                    TempData["Error"] = $"{Resources.Resources.AdminInsertFail}";
                }
                return RedirectToAction("Index");
            }
            return View(admin);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id = -1)
        {
            var result = _adminRepo.Delete(id);
            if (result == HttpStatusCode.OK)
            {
                TempData["Deleted"] = $"{Resources.Resources.AdminDelete}";
            }
            else if (result == HttpStatusCode.NotFound)
            {
                TempData["Error"] = $"{Resources.Resources.AdminNotFound}";
            }
            else if (result == HttpStatusCode.Forbidden)
            {
                TempData["Error"] = $"{Resources.Resources.DelBoss}";
            }
            else
            {
                TempData["Error"] = $"{Resources.Resources.ErrorEvent}";
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopping.Filters;
using WebShopping.Models;
using WebShopping.Repos.Implementation;
using WebShopping.Repos.Interface;

namespace WebShopping.Controllers
{
    [AuthorizeXS]
    public class CategoryController : BaseController
    {
        private readonly ICategoryRepo _categoryRepo;
        public CategoryController(ICategoryRepo categoryRepo)
        {
            _categoryRepo = categoryRepo;
        }
        public ActionResult Index()
        {
            return View(_categoryRepo.GetAll());
        }
        [HttpGet]
        [Route("Add")]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Category category)
        {
            if (ModelState.IsValid)
            {
                if (_categoryRepo.Add(category) == HttpStatusCode.OK)
                {
                    TempData["Added"] = $"{Resources.Resources.CategoryInsert}";
                }
                else
                {
                    TempData["Error"] = $"{Resources.Resources.CatInsertFail}";
                }
                return RedirectToAction("Index");
            }
            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id = -1)
        {
            var result = _categoryRepo.Delete(id);
            if (result == HttpStatusCode.OK)
            {
                TempData["Deleted"] = $"{Resources.Resources.CatDelete}";
            }
            else if (result == HttpStatusCode.NotFound)
            {
                TempData["Error"] = $"{Resources.Resources.CatNotFound}";
            }
            else
            {
                TempData["Error"] = $"{Resources.Resources.ErrorEvent}";
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id = -1)
        {
            var category = _categoryRepo.GetById(id);
            if (category is null)
            {
                TempData["Error"] = $"{Resources.Resources.CatNotFound}";
                return RedirectToAction("Index");
            }
            return View(category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                if (_categoryRepo.Update(category) == HttpStatusCode.OK)
                {
                    TempData["Added"] = $"{Resources.Resources.CatUpdate}";
                }
                else
                {
                    TempData["Error"] = $"{Resources.Resources.CatUpdateFail}";
                }
                return RedirectToAction("Index");
            }
            return View(category);
        }
    }
}

Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using WebShopping.Filters;
using WebShopping.Models;
using WebShopping.Repos.Interface;

namespace WebShopping.Controllers
{
    [AuthorizeXS]
    public class CustomerController : BaseController
    {
        private readonly ICustomerRepo _customerRepo;
        public CustomerController(ICustomerRepo customerRepo)
        {
            _customerRepo = customerRepo;
        }

        public ActionResult Index()
        {
            var customers = _customerRepo.GetAll();
            return View(customers);
        }
        [HttpGet]
        [Route("Add")]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Customer customer)
        {
            if(ModelState.IsValid)
            {
                if (_customerRepo.Add(customer) == HttpStatusCode.OK)
                {
                    TempData["Added"] = $"{Resources.Resources.CusInsert}";
                }
                else
                {
                    TempData["Error"] = $"{Resources.Resources.CusInsertFail}";
                }
                return RedirectToAction("Index");
            }
            return View(customer);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id = -1)
        {
            var result = _customerRepo.Delete(id);
            if (result == HttpStatusCode.OK)
            {
                TempData["Deleted"] = $"{Resources.Resources.CusDelete}";
            }
            else if (result == HttpStatusCode.NotFound)
            {
                TempData["Error"] = $"{Resources.Resources.CusNotFound}";
            }
            else
            {
                TempData["Error"] = $"{Resources.Resources.ErrorEvent}";
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id = -1)
        {
            var customer = _customerRepo.GetById(id);
            if(customer is null)
            {
                TempData["Error"] = $"{Resources.Resources.CusNotFound}";
                return RedirectToAction("Index");
            }
            return View(customer);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                if (_customerRepo.Update(customer) == HttpStatusCode.OK)
                {
                    TempData["Added"] = $"{Resources.Resources.CusUpdate}";
                }
                else
                {
                    TempData["Error"] = $"{Resources.Resources.CusUpdateFail}";
                }
                return RedirectToAction("Index");
            }
            return View(customer);
        }
        [HttpGet]
        [Route("Invoices")]
        public ActionResult Invoices(int id = -1)
        {
            var customer = _customerRepo.GetById(id);
            if (customer is null)
            {
                TempData["Error"] = $"{Resources.Resources.CusNotFound}";
                return RedirectToAction("Index");
            }
            return View(customer);  
        }

    }
}

Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopping.Filters;
using WebShopping.Models;
using WebShopping.ModelsView;
using WebShopping.Repos.Implementation;
using WebShopping.Repos.Interface;

namespace WebShopping.Controllers
{
    [AuthorizeXS]
    public class ItemController : BaseController
    {
        private readonly IItemRepo _itemRepo;
        private readonly ICategoryRepo _categoryRepo;
        public ItemController(IItemRepo itemRepo, ICategoryRepo categoryRepo)
        {
            _itemRepo = itemRepo;
            _categoryRepo = categoryRepo;
        }

        public ActionResult Index()
        {
            return View(_itemRepo.GetAll());
        }
        [HttpGet]
        [Route("Add")]
        public ActionResult Add()
        {
            var categories = _categoryRepo.GetAll();
            if (categories == null || categories.Count == 0)
            {
                TempData["Error"] = $"{Resources.Resources.ItemCatWarning}";
                return RedirectToAction("Index");
            }
            ViewBag.Categories = categories;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(ItemDTO item)
        {
            if (ModelState.IsValid)
            {
                var result = _itemRepo.Add(item);
                if ( result == HttpStatusCode.OK)
                {
                    TempData["Added"] = $"{Resources.Resources.ItemInsert}";
                }
                else if (result == HttpStatusCode.UnsupportedMediaType)
                {
                    ModelState.AddModelError("ImageFile", $"{Resources.Resources.ImgSupport}");
                    ViewBag.Categories = _categoryRepo.GetAll();
                    return View(item);
                }
                else if (result == HttpStatusCode.RequestEntityTooLarge)
                {
                    ModelState.AddModelError("ImageFile", $"{Resources.Resources.ImgLarge}");
                    ViewBag.Categories = _categoryRepo.GetAll();
                    return View(item);
                }
                else
                {
                    TempData["Error"] = $"{Resources.Resources.ItemInsertFail}";
                }
                return RedirectToAction("Index");
            }
            ViewBag.Categories = _categoryRepo.GetAll();
            return View(item);
        }
        [HttpGet]
        [Route("Edit")]
        public ActionResult Edit(int id = -1)
        {
            var Item = _itemRepo.GetById(id);
            if (Item is null)
            {
                TempData["Error"] = $"{Resources.Resources.ItemNotFound}";
                return RedirectToAction("Index");
            }
            var categories = _categoryRepo.GetAll();
            if (categories == null || categories.Count == 0)
            {
                TempData["Warning"] = $"{Resources.Resources.ItemCatWarning}";
                return RedirectToAction("Index");
            }
            ViewBag.Categories = categories;
            return View(Item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Item item)
        {
            ModelState["ImageURL"].Errors.Clear();
            if (ModelState.IsValid)
            {
                var itemDTO = new ItemDTO() { Amount = item.Amount, CategoryID = item.CategoryID, ID = item.ID, Description = item.Description, Name = item.Name, Price = item.Price };
                var result = _itemRepo.Update(itemDTO);
                if (result == HttpStatusCode.OK)
                {
                    TempData["Added"] = $"{Resources.Resources.ItemUpdate}";
                }
                else
                {
                    TempData["Error"] = $"{Resources.Resources.ItemUpdateFail}";
                }
                return RedirectToAction("Index");
            }
            ViewBag.Categories = _categoryRepo.GetAll();
            return View(item);
        }

        [HttpGet]
        [Route("UpdatePhoto")]
        public ActionResult UpdatePhoto(int id = -1)
        {
            var Item = _itemRepo.GetById(id);
            if (Item is null)
            {
                TempData["Error"] = $"{Resources.Resources.ItemNotFound}";
                return RedirectToAction("Index");
            }
            var itemPhoto = new UpdatePhotoDTO() { ID = id };
            return View(itemPhoto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdatePhoto(UpdatePhotoDTO item)
        {
            if (ModelState.IsValid)
            {
                var result = _itemRepo.UpdatePhotos(item);
                if (result == HttpStatusCode.OK)
                {
                    TempData["Added"] = $"{Resources.Resources.ItemPhotoUpdate}";
                }
                else if (result == HttpStatusCode.UnsupportedMediaType)
                {
                    ModelState.AddModelError("ImageFile", $"{Resources.Resources.ImgSupport}");
                    return View(item);
                }
                else if (result == HttpStatusCode.RequestEntityTooLarge)
                {
                    ModelState.AddModelError("ImageFile", $"{Resources.Resources.ImgLarge}");
                    return View(item);
                }
                else
                {
                    TempData["Error"] = $"{Resources.Resources.ItemPhotoUpdateFail}";
                }
                return RedirectToAction("Index");
            }
            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id = -1)
        {
            var result = _itemRepo.Delete(id);
            if (result == HttpStatusCode.OK)
            {
                TempData["Deleted"] = $"{Resources.Resources.ItemDelete}";
            }
            else if (result == HttpStatusCode.NotFound)
            {
                TempData["Error"] = $"{Resources.Resources.ItemNotFound}";
            }
            else
            {
                TempData["Error"] = $"{Resources.Resources.ErrorEvent}";
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/Alerts.cshtml
@if (TempData["Deleted"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>@Resources.Success</strong> @TempData["Deleted"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <strong>@Resources.Error</strong> @TempData["Error"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

@if (TempData["Added"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>@Resources.Success</strong> @TempData["Added"]
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="@WebShopping.Resources.Resources.lang" dir="@WebShopping.Resources.Resources.dir">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("css", false)
</head>
<body>

    <nav class="navbar navbar-dark navbar-expand-lg bg-dark sticky-top">
        <div class="container-fluid">
            @Html.ActionLink($"{WebShopping.Resources.Resources.StoreName}", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Outer Heaven Store</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                </div>
                <div class="offcanvas-body bg-dark">
                    <ul class="navbar-nav flex-grow-1">
                        <li>@Html.ActionLink($"{WebShopping.Resources.Resources.Home}", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink($"{Resources.About}", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                        @if (Request.Cookies["Auth"] != null && SimpleEncryptor.Decrypt(Request.Cookies["Auth"]["Boss"]) == true.ToString())
                        {
                            <li>@Html.ActionLink($"{WebShopping.Resources.Resources.Admins}", "", "Admin", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                        @if (Request.Cookies["Auth"] != null)
                        {
                            <li>@Html.ActionLink($"{WebShopping.Resources.Resources.Customers}", "", "Customer", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink($"{WebShopping.Resources.Resources.Categories}", "", "Category", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink($"{WebShopping.Resources.Resources.Items}", "", "Item", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink($"{WebShopping.Resources.Resources.Invoices}", "", "Invoice", new { area = "" }, new { @class = "nav-link" })</li>
                            <li>@Html.ActionLink($"{WebShopping.Resources.Resources.ChangePass}", "ChangePass", "Account", new { adminID = SimpleEncryptor.Decrypt(Request.Cookies["Auth"]["ID"]) }, new { @class = "nav-link" })</li>
                        }



                        @if (System.Globalization.CultureInfo.CurrentUICulture.ToString() == "ar")
                        {
                            <li class="flex-grow-1">@Html.ActionLink($"English", "ChangeLang", "Home", new { langID = 1 }, new { @class = "nav-link" })</li>
                        }
                        else
                        {
                            <li class="flex-grow-1">@Html.ActionLink($"العربية", "ChangeLang", "Home", new { langID = 2 }, new { @class = "nav-link" })</li>
                        }

                        @if (Request.Cookies["Auth"] != null)
                        {
                            <li>@Html.ActionLink($"{Resources.Logout}", "Logout", "Account", new { area = "" }, new { @class = "nav-link logoutBTN" })</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink($"{Resources.Login}", "Login", "Account", new { area = "" }, new { @class = "nav-link" })</li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - A JustOmar&trade; Application</p>
        </footer>
    </div>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary d-none mainModalBTN" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        Launch static backdrop modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="staticBackdropLabel">@Resources.Warning</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    @Resources.Timeout
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" onclick="logout()" >@Resources.No</button>
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">@Resources.OK</button>
                </div>
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @if (Request.Cookies["Auth"] != null)
    {
        <script>
            var timeout;

            document.addEventListener("mousemove", resetTimer);
            document.addEventListener("click", resetTimer);
            document.addEventListener("scroll", resetTimer);

            timeout = setTimeout(function () {
                $(".mainModalBTN").click();
            }, 2 * 60 * 1000);

            function resetTimer() {
                clearTimeout(timeout);
                timeout = setTimeout(function () {
                    $(".mainModalBTN").click();
                }, 2 * 60 * 1000);
            }

            function logout() {
                console.log("bruh");
                document.querySelector(".logoutBTN").click();
            }
        </script>
    }
</body>
</html>